name: SecondCount
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - ipykernel
  - pytorch::pytorch
  - tensorboard
  - pandas
  - requests
  - conda-forge::biopython
  - multiprocess
  - matplotlib
