name: SecondCount
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - ipykernel
  - tensorboard
  - pandas
  - requests
  - conda-forge::biopython
  - multiprocess
  - matplotlib
  - conda-forge::transformers
  - scikit-learn
  - torchmetrics
